### ISSUE TITLE
UUID Spoofing / Swapping?

### ISSUE THREAD

**Issue by ryantheleach** [astei/velocity#15]
It's been a long standing goal of mine to be able to swap between 'profiles' for a given online account.

# Usecase 1

E.g. ryantheleach owns 1 Mojang account, and has authenticated. He is a junior staff member on a server. He is in highschool, so can't afford a second account.

Our server network prefers to audit staff actions, and to make that easier, requires that all staff members have a staff account, that has completely different permissions, and mode of play. Actions taken by staff members are audited for fair play.

Spoofing UUID's of authenticated accounts, would allow junior staff member ryantheleach to play normally on the server, as well as administrating the server, without constantly flagging false positive's in the audit log, as if he had 2 accounts on the server.

# Usecase 2

It would also enable interesting gameplay, being able to swap from a "Engineer" on a build server, that builds dungeons for other users, and an "Adventurer" who runs dungeons of other Engineers. without conflating the native in-built statistics of Minecraft.

In order for both of these to work effectively, and present themselves as completely different profiles to plugins, the far 'easiest' solution is just to swap the UUID/profile completely. Custom Plugins that need to be aware of the online owner of the account, could query it via an API.

# Usecase 3

This would have the unintended side-effect of making mixed mode authentication easier, should auth servers go down, But would not completely allow it. as you could restrict the feature to authenticated accounts only.

I fully understand if you instantly close this ticket, as it's **very** close to enabling cracked server authentication via the proxy, But my instinct is **people will do this anyway** so we may as well enable the feature for those that could use it in positive ways, or Libraries that need multiple profiles for shared computers.

**Comment by astei** [comment]
I feel as if this is too niche of a feature to include in Velocity, at least right now. Support for this _might_ be added down the line, but for the moment I don't think we should consider it.

**Comment by ryantheleach** [comment]
I understand, If I took the development effort later down the line, would you be receptive to accepting it? 

I realize at the current stage of maturity, that it's unwanted.

**Comment by astei** [comment]
If you did, we would be receptive to it, yes.
